### ISSUE TITLE
Launch failed error in both VAB and SPH

### ISSUE THREAD

**Issue by DuploMinh** [GER-Space/Kerbal-Konstructs#91]
__Version__ 1.4.3.0 on KSP 1.4.3 
__OS__ Windows 10 Pro

Any attempt to launch in any Kerbal Konstruct site will result in ""Ship name" launch failed" error
Replicate: Launch anything on a KK added site
[KSP.log](https://github.com/GER-Space/Kerbal-Konstructs/files/1963848/KSP.log)

**Comment by GER-Space** [comment]
this should be fixed in the latest release: 
https://github.com/GER-Space/Kerbal-Konstructs/releases/tag/1.4.3.2

**Comment by m4ti140** [comment]
I'm still getting this error in the latest version when switching editors on the fly or trying to launch directly from the runway screen. It's not consistent though.
